name: Reusable

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
    outputs:
      result:
        value: ${{ jobs.deploy.outputs.job-output }}

jobs:
  deploy:
    outputs:
      job-output: ${{ steps.output-result.outputs.step-result }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Deploy
        run: echo 'Deploying using the reusable workflow!'
      - name: Output result
        id: output-result
        run: echo 'step-result=success' >> '$GITHUB_OUTPUT'
